config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  controller :encrypted_messages do
    post '/encrypted_messages/create', action: 'create', as: 'create_encrypted_message'
    post '/encrypted_messages/lookup', action: 'lookup', as: 'lookup_encrypted_message'
    delete '/encrypted_messages/destroy', action: 'destroy', as: 'destroy_encrypted_message'
  end
end

app/models/encrypted_message.rb
class EncryptedMessage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/encrypted_messages_controller.rb
class EncryptedMessagesController < ApplicationController
  def create
    @message = params[:msg]
    @email = params[:email]
    @pass_phrase = params[:pass_phrase]

    @encrypted_message = EncryptedMessage.new
    @encrypted_message.update_attribute(:msg, AESCrypt.encrypt(@message, @pass_phrase))
    @encrypted_message.update_attribute(:email, @email)

    if @encrypted_message.save!
      flash[:notice] = "message encrypted and saved successfully"
    else
      flash[:notice] = "something went wrong. Try again later."
    end

    redirect_to root_url
  end

  def lookup
    @msg_email = params[:msg_email]
    @pass_phrase = params[:pass_phrase]

    @encrypted_message = EncryptedMessage.find_by_email(@msg_email).msg
    @decrypted_message = AESCrypt.decrypt(@encrypted_message, @pass_phrase)

    flash[:notice] = @decrypted_message

    redirect_to root_url
  end

  def destroy
    #destroy after 24 hours or at N time
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @encrypted_message = EncryptedMessage.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encrypted_messages_helper.rb
module EncryptedMessagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/encrypted_messages/create.html.erb
<h1> create </h1>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2.col-lg-offset-2">
      <h1>Encrypted EX</h1>

      <%= form_tag create_encrypted_message_path, method: :post do %>
          <p>
        <%= label_tag :email, "Email or Alias", placeholder: 'Email or alias here...' %>
        <%= text_field_tag :email %>
          </p>
          <p>
        <%= label_tag :msg %>
        <%= text_field_tag :msg %>
          </p>
          <p>
        <%= label_tag :pass_phrase %>
        <%= password_field_tag :pass_phrase %>
          </p>

        <p>
          <%= submit_tag 'Send Msg' %>
        </p>
      <% end %>
    </div>
  </div>
  <div class="row">
    <h3>
      <strong>
        <%= flash[:notice] %>
      </strong>
    </h3>
  </div>

  <div class="row">
    <div class="col-lg-2.col-lg-offset-2">
      <%= form_tag lookup_encrypted_message_path, method: :post, class: 'form-horizontal' do %>
        <div class="form-group">
          <p>
            <%= label_tag :msg_email %>
            <%= text_field_tag :msg_email %>
          </p>
          <p>
            <%= label_tag :pass_phrase %>
            <%= password_field_tag :pass_phrase %>
          </p>

          <p>
            <%= submit_tag 'decrypte' %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Encrypted</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>